import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import LogoNav from "@/sections/logo nav/LogoNav";
import Hero from "@/sections/hero/Hero";
import ProjectsLine from "@/sections/projects line/ProjectsLine";
import Marquee from "@/sections/marquee/Marquee";
import White1 from "@/sections/white 1/White1";
import Divider1 from "@/components/dividers/Divider1/Divider1";
import Gray from "@/sections/Gray/Gray";
import Divider2 from "@/components/dividers/Divider2/Divider2";
import Benefits from "@/sections/benefits/Benefits";
import Divider3 from "@/components/dividers/Divider3/Divider3";
import Latest from "@/sections/latest/Latest";
import Divider4 from "@/components/dividers/Divider4/Divider4";
import White2 from "@/sections/white 2/White2";
import Sow from "@/sections/sow/Sow";
import Divider5 from "@/components/dividers/Divider5/Divider5";
import Pricing from "@/sections/pricing/Pricing";
import Divider6 from "@/components/dividers/Divider6/Divider6";
import FAQ from "@/sections/faq/FAQ";
import Footer from "@/sections/footer/Footer";
import Navbar from "@/components/Floating nav/Navbar";

import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Design Joy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LogoNav />
        <Hero />
        <ProjectsLine />
        <Marquee />
        <White1 />
        <Divider1 />
        <Gray />
        <Divider2 />
        <Benefits />
        <Divider3 />
        <Latest />
        <Divider4 />
        <White2 />
        <Sow />
        <Divider5 />
        <Pricing />
        <Divider6 />
        <FAQ />
        <Footer />
        {/* cookies */}
        <Navbar />
      </main>
    </>
  );
}
